// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iocvolayzhexnkcxktou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvY3ZvbGF5emhleG5rY3hrdG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODE5OTksImV4cCI6MjA1OTk1Nzk5OX0.appcrGY058bi47io4MHsEmtWnY3oot0r2KnyTapfHJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);